height = float(input("Height?"))
weight = float(input("Weight?"))
bmi = weight/(height*height)
print("Height is" + str(height) + "m")
print("Weight is" + str(weight) + "kg")
print ("BMI is" + str(bmi))